/* Original demo prompts. No private textbook excerpts or diagrams are shipped. */
globalThis.EconData = {
  units: [
    {
      id: "intro",
      number: "01",
      name: "Introduction",
      color: "yellow",
      icon: "lightbulb",
      image: "assets/market.jpg",
      description: "Scarcity, choice & the economic way of thinking",
    },
    {
      id: "micro",
      number: "02",
      name: "Microeconomics",
      color: "green",
      icon: "store",
      image: "assets/market.jpg",
      description: "Markets, incentives & the choices we make",
    },
    {
      id: "macro",
      number: "03",
      name: "Macroeconomics",
      color: "blue",
      icon: "landmark",
      image: "assets/city.jpg",
      description: "The big picture: output, prices & policy",
    },
    {
      id: "global",
      number: "04",
      name: "The global economy",
      color: "pink",
      icon: "globe-2",
      image: "assets/trade.jpg",
      description: "Trade, currencies & economic development",
    },
  ],
  cards: [
    {
      id: "negative-externalities",
      unit: "micro",
      title: "The price we don't pay",
      topic: "Negative externalities",
      tag: "Market failure",
      visual: "externality",
      question:
        "A factory's pollution harms nearby residents. Why can the market produce too much?",
      answer:
        "The firm considers its private costs, but not all of the costs imposed on residents. Marginal social cost exceeds marginal private cost, so market output can exceed the socially efficient quantity.",
      takeaway: "Private cost + external cost = social cost",
      trap: "This is a production externality. A consumption externality uses a different benefit-side diagram.",
      rubric: [
        "Identifies a cost borne by third parties",
        "Distinguishes social from private marginal cost",
        "Links the unpriced cost to excessive market output",
      ],
      related: ["market-failure", "price-elasticity"],
      source: "Original demo scenario",
      version: 1,
    },
    {
      id: "price-elasticity",
      unit: "micro",
      title: "How much is too much?",
      topic: "Price elasticity of demand",
      tag: "Elasticity",
      visual: "elasticity",
      question:
        "Price rises by 10%. Quantity demanded falls by 20%. What is PED, and how responsive is demand?",
      answer:
        "PED is -20% / 10% = -2. Its magnitude is 2, greater than 1, so demand is price elastic: quantity demanded changes proportionately more than price.",
      takeaway: "|PED| = 2  /  Elastic demand",
      trap: "The negative sign describes the direction. The magnitude describes responsiveness.",
      rubric: [
        "Divides percentage quantity change by percentage price change",
        "Calculates -2, or states magnitude 2",
        "Interprets demand as price elastic",
      ],
      related: ["demand", "market-failure"],
      source: "Original demo calculation",
      version: 1,
    },
    {
      id: "demand",
      unit: "micro",
      title: "A move, not a shift",
      topic: "Demand and quantity demanded",
      tag: "Demand & supply",
      visual: "demand",
      question:
        "The price of coffee falls. Other determinants are unchanged. Does its demand curve shift?",
      answer:
        "No. A change in the good's own price causes a movement along the existing demand curve. With ordinary downward-sloping demand, the lower price increases quantity demanded.",
      takeaway: "Own-price change = movement along demand",
      trap: "An income or preference change can shift demand. A change in the good's own price does not.",
      rubric: [
        "States that the curve does not shift",
        "Identifies a movement along the curve",
        "States that quantity demanded increases",
      ],
      related: ["price-elasticity"],
      source: "Original demo scenario",
      version: 1,
    },
    {
      id: "market-failure",
      unit: "micro",
      title: "When markets miss",
      topic: "Market failure",
      tag: "Market failure",
      visual: "externality",
      question:
        "Does market failure mean that no buying or selling takes place?",
      answer:
        "No. Trade may continue, but the market allocation is inefficient. For example, an unpriced external cost can mean output exceeds the socially efficient level.",
      takeaway: "A functioning market can still be inefficient",
      trap: "A firm making a loss is not, by itself, evidence of market failure.",
      rubric: [
        "Rejects the idea that trade must stop",
        "Identifies inefficient resource allocation",
      ],
      related: ["negative-externalities"],
      source: "Original demo prompt",
      version: 1,
    },
    {
      id: "inflation",
      unit: "macro",
      title: "Prices are still rising",
      topic: "Inflation and disinflation",
      tag: "Price stability",
      visual: "inflation",
      question: "Annual inflation falls from 6% to 3%. Have prices fallen?",
      answer:
        "No. The general price level is still rising, but at a slower rate. That is disinflation. Deflation would mean a fall in the general price level.",
      takeaway: "Lower inflation ≠ lower prices",
      trap: "These rates describe changes in the general price level, not the price of every individual good.",
      rubric: [
        "States that the price level still rises",
        "Names disinflation",
        "Distinguishes it from deflation",
      ],
      related: ["real-gdp"],
      source: "Original demo scenario",
      version: 1,
    },
    {
      id: "real-gdp",
      unit: "macro",
      title: "Beyond the price tag",
      topic: "Real and nominal GDP",
      tag: "Measuring output",
      visual: "gdp",
      question:
        "Nominal GDP rises by 5%, while all output prices rise by 5%. If quantities stay the same, has real output grown?",
      answer:
        "No. The increase in nominal GDP is explained by higher prices. Real GDP values output at constant prices, so unchanged quantities mean unchanged real output in this example.",
      takeaway: "Real GDP separates output from price changes",
      trap: "Real GDP per capita also adjusts for population. It is a different measure from total real GDP.",
      rubric: [
        "States that real output has not grown",
        "Explains the constant-price distinction",
      ],
      related: ["inflation", "development"],
      source: "Original simplified demo scenario",
      version: 1,
    },
    {
      id: "exchange-rates",
      unit: "global",
      title: "One currency, two sides",
      topic: "Exchange rates",
      tag: "Currencies",
      visual: "currency",
      question:
        "A currency appreciates. What happens to import prices in domestic currency, with foreign prices unchanged?",
      answer:
        "Imports become cheaper in domestic currency because each unit of domestic currency buys more foreign currency. Export prices in foreign currency may rise if domestic-currency export prices stay unchanged.",
      takeaway: "A stronger currency buys more abroad",
      trap: "The effect on the trade balance also depends on elasticities, timing, and other conditions.",
      rubric: [
        "Identifies cheaper imports in domestic currency",
        "Explains increased purchasing power over foreign currency",
      ],
      related: ["price-elasticity", "development"],
      source: "Original demo prompt",
      version: 1,
    },
    {
      id: "development",
      unit: "global",
      title: "More than a bigger economy",
      topic: "Economic development",
      tag: "Development",
      visual: "development",
      question:
        "Can GDP per capita rise without a comparable improvement in most people's lives?",
      answer:
        "Yes. Average income can rise while gains are concentrated among a small group. Health, education, inequality, and environmental conditions also matter when assessing development.",
      takeaway: "An average does not show the distribution",
      trap: "GDP per capita is useful, but it is not a complete measure of wellbeing.",
      rubric: [
        "Explains that an average can hide inequality",
        "Identifies at least one non-income dimension",
      ],
      related: ["real-gdp"],
      source: "Original demo prompt",
      version: 1,
    },
    {
      id: "opportunity-cost",
      unit: "intro",
      title: "Every yes has a no",
      topic: "Opportunity cost",
      tag: "Scarcity & choice",
      visual: "choice",
      question:
        "You have one free hour and choose to revise instead of your next-best option: playing football. What is the opportunity cost?",
      answer:
        "The value of the football time you give up. Opportunity cost is the value of the next-best alternative forgone, rather than the sum of every possible alternative.",
      takeaway: "The next-best alternative forgone",
      trap: "Opportunity cost can involve time or enjoyment, not only money.",
      rubric: [
        "Identifies the forgone football time",
        "Refers to the next-best alternative",
      ],
      related: ["scarcity"],
      source: "Original demo scenario",
      version: 1,
    },
    {
      id: "scarcity",
      unit: "intro",
      title: "Why choices exist",
      topic: "Scarcity",
      tag: "Scarcity & choice",
      visual: "choice",
      question: "Why does scarcity exist even in a wealthy economy?",
      answer:
        "Resources are finite relative to people's wants. A wealthy economy has more resources, but still faces choices about how to allocate time, labour, land, and capital.",
      takeaway: "Finite resources. Competing wants.",
      trap: "Scarcity is the underlying constraint; a shortage is a market situation at a particular price.",
      rubric: [
        "Identifies limited resources relative to wants",
        "Links scarcity to allocation choices",
      ],
      related: ["opportunity-cost"],
      source: "Original demo prompt",
      version: 1,
    },
  ],
};
